//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubmitBug.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TB_BugSubmit
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int BId { get; set; }
        [Required]
        [MaxLength(50), Display(Name = "程序名称")]
        public string AppName { get; set; }
        [Required]
        [DataType(DataType.MultilineText)]
        [MaxLength(500), Display(Name = "问题描述")]
        public string Describe { get; set; }
        [Required]
        [MaxLength(50), Display(Name = "联系人")]
        public string Claimant { get; set; }
        [Required]
        [MaxLength(50), Display(Name = "联系电话")]
        [RegularExpression(@"^[0-9-()]*$", ErrorMessage = "电话号码输入不符合规则!")]
        public string LPhone { get; set; }
        [Required]
        [MaxLength(20), Display(Name = "电脑编号")]
        public string ComputerNo { get; set; }
        
        [Display(Name = "提交时间")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public System.DateTime SubDate { get; set; }
        
        [MaxLength(50), Display(Name = "登录IP")]
        public string LIP { get; set; }
        
        [MaxLength(2), DefaultValue("N"), Display(Name = "是否完成")]
        public string YN { get; set; }
        
        
    
        public virtual TB_LoginOn LoginOn { get; set; }
        [Display(Name = "登录ID"), DefaultValue(1)]
        public int LId { get; set; }
        public virtual ICollection<TB_Follow> Follow { get; set; }

        public virtual ICollection<TB_Schedule> Schedule { get; set; }

        
    }
}
