//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubmitBug.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TB_LoginOn
    {
        public TB_LoginOn()
        {
            this.BugSubmit = new HashSet<TB_BugSubmit>();
            this.Follow = new HashSet<TB_Follow>();
            this.UserFace = new HashSet<TB_UserFace>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int LId { get; set; }
        [Required]
        [MaxLength(20), Display(Name = "工号")]
        public string LoginNo { get; set; }
        [Required]
        [MaxLength(50), Display(Name = "姓名")]
        public string LoginName { get; set; }
        [Required]
        [MaxLength(50), Display(Name = "密码"),DataType(DataType.Password)]
        public string LoginPwd { get; set; }
        [Required]
        [MaxLength(50), Display(Name = "联系电话")]
        [RegularExpression(@"^[0-9-]*$", ErrorMessage ="电话号码输入不符合规则!")]
        public string LPhone { get; set; }
        [Required,]
        [MaxLength(20), Display(Name = "电脑编号")]
        public string ComputerNo { get; set; }

        [DefaultValue(1),Display(Name = "权限")]
        public int AId { get; set; } 
    
        public virtual ICollection<TB_BugSubmit> BugSubmit { get; set; }
        public virtual ICollection<TB_Follow> Follow { get; set; }

        public virtual ICollection<TB_UserFace> UserFace { get; set; }

        public virtual TB_UserAccess UserAccess { get; set; }
    }
}
