//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubmitBug.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TB_UserAccess
    {
        
        public TB_UserAccess()
        {
            this.LoginOn = new HashSet<TB_LoginOn>();
            this.ShowMenus = new HashSet<TB_ShowMenu>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int AId { get; set; }
        [Required]
        [MaxLength(20), Display(Name = "权限")]
        public string AccessName { get; set; }
    
        
        public virtual ICollection<TB_LoginOn> LoginOn { get; set; }

        public virtual ICollection<TB_ShowMenu> ShowMenus { get; set; }
    }
}
